export const authConstants = {
	USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
	USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
	USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
	USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
	USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
	USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',
};

export const userConstants = {
	GET_REALTIME_USERS_REQUEST: 'GET_REALTIME_USERS_REQUEST',
	GET_REALTIME_USERS_SUCCESS: 'GET_REALTIME_USERS_SUCCESS',
	GET_REALTIME_USERS_FAILURE: 'GET_REALTIME_USERS_FAILURE',
	GET_REALTIME_MESSAGES_REQUEST: 'GET_REALTIME_MESSAGES_REQUEST',
	GET_REALTIME_MESSAGES_SUCCESS: 'GET_REALTIME_MESSAGES_SUCCESS',
	GET_REALTIME_MESSAGES_FAILURE: 'GET_REALTIME_MESSAGES_FAILURE',
};
