export const authConstant = {
	USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
	USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
	USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
	USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
	USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
	USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',
};
